/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    war
    id("com.palantir.docker") version "0.35.0"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web:2.1.7.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:2.1.7.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-security:2.1.7.RELEASE")
    implementation("javax.servlet:jstl:1.2")
    implementation("org.webjars:bootstrap:3.3.6")
    implementation("org.webjars:bootstrap-datepicker:1.0.1")
    implementation("org.webjars:jquery:1.9.1")
    implementation("com.h2database:h2:1.4.199")
    implementation("org.springframework.boot:spring-boot-devtools:2.1.7.RELEASE")
    implementation("org.apache.tomcat.embed:tomcat-embed-jasper:9.0.22")
    implementation("org.springframework.boot:spring-boot-starter-tomcat:2.1.7.RELEASE")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.1.7.RELEASE")
}

group = "com.in28minutes.springboot.web"
version = "0.0.1-SNAPSHOT"
description = "todo-web-application-h2"
java.sourceCompatibility = JavaVersion.VERSION_1_8

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.jar {
    enabled = false
}

val war = tasks.named("war").get()

tasks.getByName("dockerPrepare", Copy::class) {
    dependsOn(war)
    from(war.outputs.files.singleFile)
    into("build/docker")
    duplicatesStrategy = DuplicatesStrategy.FAIL
}

docker {
    name = "dau47/02-todo-web-application-h2:$version"
    dependsOn(war)
    buildArgs(mapOf("WAR_FILE" to war.outputs.files.singleFile.name))
    push(true)
    noCache(true)
}
