spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  config:
    activate:
      on-profile: local